### ISSUE TITLE
Fail on Bikeshed errors

### ISSUE THREAD

**Issue by mkruisselbrink** [w3c/spec-prod#20]
Similar to #19, it should be considered a failure if bikeshed reports link errors (such as in https://github.com/w3c/FileAPI/pull/160/checks?check_run_id=1745772417)

Ideally with configurable values for bikeshed's --die-on option so different specs can treat different error levels as fatal.

**Comment by dontcallmedom** [comment]
I don't know if it's the documentation that is wrong or the code, but setting `BUILD_FAIL_ON: link-error` in a spec-prod config for a bikeshed document results into the following command being run `bikeshed spec "index.bs" "index.bs.built.html" --die-on=link-error` instead of `--die-on=error`, which means it doesn't fail.

**Comment by sidvishnoi** [comment]
`BUILD_FAIL_ON` is a one-to-one mapping over bikeshed's `--die-on`. So, the docs are wrong here. Fixed in https://github.com/w3c/spec-prod/commit/0b3957d5601391bf0b9c19f514a989e64454570e.
(credits to me for using multi-cursor incorrectly)

**Comment by dontcallmedom** [comment]
hmm... but then, bikeshed doesn't seem to be dying on LINK_ERROR when using `--die-on=link-error`? https://github.com/w3c/webrtc-insertable-streams/runs/2055726226?check_suite_focus=true#step:3:116

**Comment by dontcallmedom** [comment]
ah, it looks like `die-on=link-error` needs to be specified **before** the command (`spec`)

**Comment by sidvishnoi** [comment]
Ah. That makes sense, as it's a "global option". Sending fix...
