### ISSUE TITLE
w3c-deploy: publishing fails if tried multiple times on same day

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/spec-prod#41]
Investigate https://github.com/w3c/spec-prod/pull/33#discussion_r593720548

**Comment by sidvishnoi** [comment]
Looks like the logic was reversed: https://github.com/w3c/spec-prod/blob/35bafa7d8bb0b4bf72dbdff03c10f171b1b2f12f/src/prepare-build.ts#L294-L295

Should be:
```diff
const currentURI = 
-	thisDate === targetPublishDate && previousURI ? previousURI : thisURI;
+	thisDate === targetPublishDate || !previousURI ? thisURI : previousURI;
```

**Comment by sidvishnoi** [comment]
@deniak Can you help me with this one? The earlier logic was copied from spec-generator; but it doesn't seem to work here.

**Comment by deniak** [comment]
Actually, the earlier logic seems to be the good one. If the document was already published on that same day, then, the previous version *is* the previous version fetched from the shortlink (/TR/@shortname@).
I believe the earlier error reported in https://github.com/w3c/spec-prod/pull/33#discussion_r593720548 was fixed by https://github.com/w3c/webappsec-csp/commit/f7c1d01c36f78cb8d5e4d27a1f243cee43b94311#diff-9c9742da767c9cdb571630db3d8b80d32c1a50fc713a9944b0cb6503c521c2c8

Running the `prepare-build` on `main` produces the expected result.

**Comment by sidvishnoi** [comment]
Thank you @deniak!
This is then probably due to https://github.com/tabatkins/bikeshed/issues/2041.

**Comment by sidvishnoi** [comment]
Can also confirm from https://lists.w3.org/Archives/Public/public-tr-notifications/2021Apr/
![image](https://user-images.githubusercontent.com/8426945/116397499-468fbe00-a844-11eb-8313-588b9cfc72d7.png)
