### ISSUE TITLE
Build respec snapshots

### ISSUE THREAD

**Issue by jyasskin** [w3c/spec-prod#94]
https://github.com/w3ctag/privacy-principles/blob/main/.github/workflows/auto-publish.yml uses spec-prod's respec mode, but the output at https://w3ctag.github.io/privacy-principles/ is identical to the [source](https://github.com/w3ctag/privacy-principles/blob/main/index.html), rather than being the built snapshot you get by using respec's [export](https://respec.org/docs/#static-snapshots) tool. The current state makes the published version break when dependencies change, and it shows readers a flash-of-unbuilt-content every time they load a page.

**Comment by sidvishnoi** [comment]
The issue here is the repository is configured to deploy GitHub pages from "main" branch, and not "gh-pages". `gh-pages` branch correctly has the static snapshot. See https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

<details>
<summary>Find current publishing source for a repo</summary>

```bash
gh api repos/w3ctag/privacy-principles/pages --jq '.source.branch'
#> main
```

</details>

**Comment by jyasskin** [comment]
Thanks, and sorry for the noise.

**Comment by sidvishnoi** [comment]
No worries 🙂
